### ISSUE TITLE
Provide timezone customization

### ISSUE THREAD

**Issue by taogilaaa** [warungpintar/workplace-incoming-hook#11]
The current message implementation sends the timezone as UTC, we should provide a configuration option to adjust printed time

**Comment by jojoarianto** [comment]
bug when gitlab push time message not convert correctly 
output 

```
Push on dag_script by Faishal Nuruz Zuhri
at 2019-07-18T15:56:45Z 
on branch refs/heads/fais-etl-stag:
...
```

**Comment by enrinal** [comment]
I think this issue can be closed
